#!/usr/bin/python3
from Crypto.PublicKey import RSA

key = RSA.generate(2048)


def generatePublicKey():

    public_key = key.publickey().export_key()
    f = open("public.pem", "wb")
    f.write(public_key)
    f.close()


def generatePrivateKey():
    private_key = key.export_key()
    f = open("private.pem", "wb")
    f.write(private_key)
    f.close()


# # # # # Main # # # # #
generatePrivateKey()
generatePublicKey()
print("Successfully generated private and public RSA keys.")

